name: Generate {{NAME}}

on:
  schedule:
    - cron: '0 1 * * 1-5'   # 每个工作日 UTC 01:00（可按需修改）
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      DATE: ${{ github.event.inputs.date || '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run script
        run: |
          if [ -n "${{ github.event.inputs.date }}" ]; then
            DATE="${{ github.event.inputs.date }}"
          else
            DATE=$(date -u +%F)
          fi
          chmod +x ./.agents/skills/{{NAME}}/run.sh
          ./.agents/skills/{{NAME}}/run.sh "${DATE}" "agent / github-actions"
      - name: Create Pull Request (if changes)
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Create {{NAME}} output: ${{ env.DATE }}"
          branch: "{{NAME}}-output-${{ env.DATE }}"
          title: "Create {{NAME}} output: ${{ env.DATE }}"
          body: "Auto-generated by workflow for {{NAME}}"
